# Generated by Django 5.1.5 on 2025-01-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_de_estudio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacionGrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Visualización Principal', max_length=100)),
                ('config_global', models.JSONField(default=dict, help_text='Representación de la configuracion global del grafo.')),
                ('plan_de_estudio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizacion_grafo', to='plan_de_estudio.plandeestudio')),
            ],
            options={
                'verbose_name': 'Configuración del Grafo',
                'verbose_name_plural': 'Configuraciones de Grafos',
            },
        ),
        migrations.CreateModel(
            name='NodoGrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('config_visual', models.JSONField(default=dict, help_text='Configuración para visualizacion del nodo.')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.materia')),
                ('grafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='visualizacion_grafo.visualizaciongrafo')),
            ],
        ),
        migrations.CreateModel(
            name='EnlaceGrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_visual', models.JSONField(default=dict, help_text='Configuración para visualizacion del enlace entre nodos.')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_entrantes', to='visualizacion_grafo.nodografo')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_salientes', to='visualizacion_grafo.nodografo')),
                ('grafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='visualizacion_grafo.visualizaciongrafo')),
            ],
        ),
    ]
