# Generated by Django 5.1.5 on 2025-02-04 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadPlanificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion_horario', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('CLASE', 'Clase'), ('EXAMEN', 'Examen'), ('CONSULTA', 'Consulta'), ('ENTREGA', 'Entrega de TP'), ('RECUPERATORIO', 'Recuperatorio')], max_length=20)),
                ('aula', models.CharField(max_length=50)),
                ('profesor', models.CharField(max_length=100)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('recursos', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Eventos académicos',
                'ordering': ['materia', 'dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoCalendarioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('todo_el_dia', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('actividad', 'Actividad'), ('tarea', 'Tarea'), ('materia', 'Materia'), ('meta', 'Meta Académica'), ('recordatorio', 'Recordatorio')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('RENDIMIENTO', 'Objetivo de rendimiento'), ('TIEMPO', 'Gestión de tiempo'), ('ENTREGA', 'Entrega de trabajos'), ('AUTOEVALUACION', 'Autoevaluación')], max_length=20)),
                ('fecha_limite', models.DateTimeField()),
                ('prioridad', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('CUATRIMESTRAL', 'Cuatrimestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('cuatrimestre', models.CharField(blank=True, choices=[('1', 'Cuatrimestre 1'), ('2', 'Cuatrimestre 2')], max_length=1, null=True)),
                ('año', models.IntegerField()),
                ('semana', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_estudiadas', models.PositiveIntegerField(default=0)),
                ('temas_completados', models.PositiveIntegerField(default=0)),
                ('ejercicios_resueltos', models.PositiveIntegerField(default=0)),
                ('autoevaluaciones', models.PositiveIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordatorioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('repetir', models.CharField(choices=[('UNA_VEZ', 'Una vez'), ('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='UNA_VEZ', max_length=10)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Notificación push'), ('SMS', 'Mensaje SMS')], default='PUSH', max_length=5)),
            ],
        ),
    ]
