# Generated by Django 5.1.5 on 2025-01-28 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento_academico', '0001_initial'),
        ('plan_de_estudio', '0001_initial'),
        ('planificadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('RENDIMIENTO', 'Objetivo de rendimiento'), ('TIEMPO', 'Gestión de tiempo'), ('ENTREGA', 'Entrega de trabajos'), ('AUTOEVALUACION', 'Autoevaluación')], max_length=20)),
                ('fecha_limite', models.DateTimeField()),
                ('prioridad', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlanificacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('CUATRIMESTRAL', 'Cuatrimestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('cuatrimestre', models.CharField(blank=True, choices=[('1', 'Cuatrimestre 1'), ('2', 'Cuatrimestre 2')], max_length=1, null=True)),
                ('año', models.IntegerField()),
                ('semana', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_estudiadas', models.PositiveIntegerField(default=0)),
                ('temas_completados', models.PositiveIntegerField(default=0)),
                ('ejercicios_resueltos', models.PositiveIntegerField(default=0)),
                ('autoevaluaciones', models.PositiveIntegerField(default=0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordatorioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('repetir', models.CharField(choices=[('UNA_VEZ', 'Una vez'), ('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='UNA_VEZ', max_length=10)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Notificación push'), ('SMS', 'Mensaje SMS')], default='PUSH', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='actividadplanificada',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificadores.evento'),
        ),
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('evento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planificadores.evento')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion_horario', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('CLASE', 'Clase'), ('EXAMEN', 'Examen'), ('CONSULTA', 'Consulta'), ('ENTREGA', 'Entrega de TP'), ('RECUPERATORIO', 'Recuperatorio')], max_length=20)),
                ('aula', models.CharField(max_length=50)),
                ('profesor', models.CharField(max_length=100)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('recursos', models.TextField(blank=True, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='plan_de_estudio.materia')),
            ],
            options={
                'verbose_name_plural': 'Eventos académicos',
                'ordering': ['materia', 'dia', 'hora_inicio'],
            },
            bases=('planificadores.evento', models.Model),
        ),
        migrations.CreateModel(
            name='EventoAsociadoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('EXAMEN_MATERIA', 'Examen → Materia'), ('ENTREGA_TP', 'Entrega → Trabajo Práctico'), ('CLASE_PRACTICA', 'Clase Práctica → Teórica'), ('RECUPERATORIO', 'Recuperatorio → Evaluación')], max_length=20)),
                ('peso', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('evento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_destino', to='evento_academico.eventoacademico')),
                ('evento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_origen', to='evento_academico.eventoacademico')),
            ],
        ),
    ]
