# Generated by Django 5.1.5 on 2025-02-04 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('evento_academico', '0001_initial'),
        ('plan_de_estudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacademico',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='plan_de_estudio.materia'),
        ),
        migrations.AddField(
            model_name='actividadplanificada',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_planificadas', to='evento_academico.eventoacademico'),
        ),
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
