# Generated by Django 5.1.5 on 2025-01-28 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento_academico', '0002_initial'),
        ('plan_de_estudio', '0001_initial'),
        ('planificadores', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metaacademica',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metaacademica',
            name='relacion_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_de_estudio.materiaestudiante'),
        ),
        migrations.AddField(
            model_name='planificacionacademica',
            name='actividades',
            field=models.ManyToManyField(through='evento_academico.ActividadPlanificada', to='planificadores.evento'),
        ),
        migrations.AddField(
            model_name='planificacionacademica',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividadplanificada',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento_academico.planificacionacademica'),
        ),
        migrations.AddField(
            model_name='progresomateria',
            name='materia_estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='plan_de_estudio.materiaestudiante'),
        ),
        migrations.AddField(
            model_name='recordatoriopersonalizado',
            name='relacion_evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificadores.evento'),
        ),
        migrations.AddField(
            model_name='recordatoriopersonalizado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='eventoasociadoacademico',
            unique_together={('evento_origen', 'evento_destino')},
        ),
        migrations.AlterUniqueTogether(
            name='actividadplanificada',
            unique_together={('planificacion', 'evento')},
        ),
    ]
