# Generated by Django 5.1.5 on 2025-02-04 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento_academico', '0002_initial'),
        ('plan_de_estudio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='metaacademica',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metaacademica',
            name='relacion_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_de_estudio.materiaestudiante'),
        ),
        migrations.AddField(
            model_name='planificacionacademica',
            name='actividades',
            field=models.ManyToManyField(through='evento_academico.ActividadPlanificada', to='evento_academico.eventoacademico'),
        ),
        migrations.AddField(
            model_name='planificacionacademica',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividadplanificada',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_planificadas', to='evento_academico.planificacionacademica'),
        ),
        migrations.AddField(
            model_name='progresomateria',
            name='materia_estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progreso', to='plan_de_estudio.materiaestudiante'),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='recurrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento_academico.recurrencia'),
        ),
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='evento_academico.tipoevento'),
        ),
        migrations.AddField(
            model_name='eventoacademico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='evento_academico.tipoeventoacademico'),
        ),
        migrations.AlterUniqueTogether(
            name='actividadplanificada',
            unique_together={('planificacion', 'evento')},
        ),
    ]
