# Generated by Django 5.1.5 on 2025-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento_academico', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='class_names',
            field=models.CharField(blank=True, help_text='Clases CSS adicionales.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='display',
            field=models.CharField(choices=[('block', 'Bloque'), ('list-item', 'Elemento de lista'), ('background', 'Fondo'), ('none', 'Oculto')], default='block', help_text='Controla cómo se muestra el evento.', max_length=20),
        ),
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='duration_editable',
            field=models.BooleanField(default=True, help_text='Indica si la duración es editable.'),
        ),
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='editable',
            field=models.BooleanField(default=True, help_text='Indica si el evento es editable.'),
        ),
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='exdate',
            field=models.CharField(blank=True, help_text='Fechas excluidas de la recurrencia.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='resource_editable',
            field=models.BooleanField(default=False, help_text='Indica si el evento puede moverse entre recursos.'),
        ),
        migrations.AddField(
            model_name='eventocalendarioacademico',
            name='start_editable',
            field=models.BooleanField(default=True, help_text='Indica si la fecha/hora de inicio es editable.'),
        ),
    ]
