# Generated by Django 5.1.5 on 2025-02-04 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('evento_academico', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fila', models.IntegerField(help_text='Número de la fila en la cuadrícula.')),
                ('columna', models.IntegerField(help_text='Número de la columna en la cuadrícula.')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del estado (por ejemplo, Pendiente, En Progreso, Completado).', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del estado.', null=True)),
                ('color', models.CharField(default='#FFFFFF', help_text='Color asociado al estado.', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de prioridad del estado.')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EstructuraPlanificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('configuracion', models.JSONField(default=dict)),
                ('filas', models.PositiveIntegerField(default=1, help_text='Número total de filas de la cuadrícula.')),
                ('columnas', models.PositiveIntegerField(default=1, help_text='Número total de columnas de la cuadrícula.')),
                ('ancho_columna', models.PositiveIntegerField(default=100, help_text='Ancho de las columnas en píxeles.')),
                ('tabla', models.JSONField(default=dict, help_text='Representación de la tabla como diccionario.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('celda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='planificadores.celda')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID de la entidad a la que está asociado el objetivo.')),
                ('descripcion', models.TextField(help_text='Descripción del objetivo.')),
                ('fecha_objetivo', models.DateField(help_text='Fecha límite para cumplir el objetivo.')),
                ('completado', models.BooleanField(default=False, help_text='Indica si el objetivo ha sido completado.')),
                ('content_type', models.ForeignKey(help_text='Tipo de la entidad a la que está asociado el objetivo.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Planificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID de la entidad asociada al planificador.', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo de la entidad asociada al planificador.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('estructura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificadores.estructuraplanificador')),
            ],
        ),
        migrations.AddField(
            model_name='celda',
            name='planificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celdas', to='planificadores.planificador'),
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio_estado', models.DateTimeField(auto_now=True, help_text='Fecha del último cambio de estado.')),
                ('nombre', models.CharField(help_text='Nombre de la actividad.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la actividad.', null=True)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio de la actividad.', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización de la actividad.', null=True)),
                ('color', models.CharField(default='#0000FF', help_text='Color asociado a la actividad.', max_length=7)),
                ('evento_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evento_academico.eventoacademico')),
                ('estado', models.ForeignKey(blank=True, help_text='Estado actual de la entidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificadores.estado')),
                ('planificador', models.ForeignKey(help_text='Planificador al que pertenece la actividad.', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='planificadores.planificador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio_estado', models.DateTimeField(auto_now=True, help_text='Fecha del último cambio de estado.')),
                ('nombre', models.CharField(help_text='Nombre de la tarea.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la tarea.', null=True)),
                ('fecha_limite', models.DateField(blank=True, help_text='Fecha límite para completar la tarea.', null=True)),
                ('color', models.CharField(default='#FF0000', help_text='Color asociado a la tarea.', max_length=7)),
                ('esta_realizada', models.BooleanField(default=False, help_text='Indica si la tarea está completada')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(help_text='Actividad asociada.', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='planificadores.actividad')),
                ('estado', models.ForeignKey(blank=True, help_text='Estado actual de la entidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificadores.estado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
