# Generated by Django 5.1.5 on 2025-01-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio_estado', models.DateTimeField(auto_now=True, help_text='Fecha del último cambio de estado.')),
                ('nombre', models.CharField(help_text='Nombre de la actividad.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la actividad.', null=True)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio de la actividad.', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización de la actividad.', null=True)),
                ('color', models.CharField(default='#0000FF', help_text='Color asociado a la actividad.', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('fila', models.IntegerField(help_text='Número de la fila en la cuadrícula.')),
                ('columna', models.IntegerField(help_text='Número de la columna en la cuadrícula.')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del estado (por ejemplo, Pendiente, En Progreso, Completado).', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del estado.', null=True)),
                ('color', models.CharField(default='#FFFFFF', help_text='Color asociado al estado.', max_length=7)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de prioridad del estado.')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EstructuraElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('configuracion', models.JSONField(default=dict)),
                ('fecha_edicion', models.DateTimeField(auto_now=True)),
                ('html_visualizacion', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstructuraPlanificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('configuracion', models.JSONField(default=dict)),
                ('filas', models.PositiveIntegerField(default=1, help_text='Número total de filas de la cuadrícula.')),
                ('columnas', models.PositiveIntegerField(default=1, help_text='Número total de columnas de la cuadrícula.')),
                ('ancho_columna', models.PositiveIntegerField(default=100, help_text='Ancho de las columnas en píxeles.')),
                ('tabla', models.JSONField(default=dict, help_text='Representación de la tabla como diccionario.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#FFFFFF', help_text='Color en formato hexadecimal', max_length=7)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la etiqueta', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(help_text='ID de la entidad a la que está asociado el objetivo.')),
                ('descripcion', models.TextField(help_text='Descripción del objetivo.')),
                ('fecha_objetivo', models.DateField(help_text='Fecha límite para cumplir el objetivo.')),
                ('completado', models.BooleanField(default=False, help_text='Indica si el objetivo ha sido completado.')),
            ],
        ),
        migrations.CreateModel(
            name='Planificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID de la entidad asociada al planificador.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=50)),
                ('proxima_fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de progreso.', max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró el progreso.')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio_estado', models.DateTimeField(auto_now=True, help_text='Fecha del último cambio de estado.')),
                ('nombre', models.CharField(help_text='Nombre de la tarea.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la tarea.', null=True)),
                ('fecha_limite', models.DateField(blank=True, help_text='Fecha límite para completar la tarea.', null=True)),
                ('color', models.CharField(default='#FF0000', help_text='Color asociado a la tarea.', max_length=7)),
                ('esta_realizada', models.BooleanField(default=False, help_text='Indica si la tarea está completada')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
