# Generated by Django 5.1.5 on 2025-01-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento_academico', '0002_initial'),
        ('planificadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='evento_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evento_academico.eventoacademico'),
        ),
    ]
