# Generated by Django 5.1.4 on 2024-12-26 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('planificadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elemento',
            name='celda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='planificadores.celda'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado actual de la entidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificadores.estado'),
        ),
        migrations.AddField(
            model_name='elemento',
            name='estructura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificadores.estructuraelemento'),
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoasociado',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='eventoasociado',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asociaciones', to='planificadores.evento'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='content_type',
            field=models.ForeignKey(help_text='Tipo de la entidad a la que está asociado el objetivo.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='planificador',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de la entidad asociada al planificador.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='planificador',
            name='estructura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificadores.estructuraplanificador'),
        ),
        migrations.AddField(
            model_name='celda',
            name='planificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celdas', to='planificadores.planificador'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='planificador',
            field=models.ForeignKey(help_text='Planificador al que pertenece la actividad.', on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='planificadores.planificador'),
        ),
        migrations.AddField(
            model_name='registroprogreso',
            name='actividad',
            field=models.ForeignKey(help_text='Actividad asociada al registro.', on_delete=django.db.models.deletion.CASCADE, related_name='registros_progreso', to='planificadores.actividad'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='actividad',
            field=models.ForeignKey(help_text='Actividad asociada.', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='planificadores.actividad'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado actual de la entidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='planificadores.estado'),
        ),
    ]
