# Generated by Django 5.1.4 on 2024-12-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificadores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estructuraplanificador',
            name='tabla',
            field=models.JSONField(default=dict, help_text='Representación de la tabla como diccionario.'),
        ),
    ]
