# Generated by Django 5.1.5 on 2025-01-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificadores', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
