# Generated by Django 5.1.5 on 2025-01-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificadores', '0004_alter_evento_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_hora',
            field=models.DateTimeField(null=True),
        ),
    ]
