# Generated by Django 5.1.4 on 2024-12-26 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDeEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('año_creacion', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ['año_creacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('ciclo', models.CharField(blank=True, max_length=50, null=True)),
                ('cuatrimestre', models.IntegerField(blank=True, null=True)),
                ('condicion', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=1000)),
                ('formato_didactico', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_semanal', models.IntegerField(blank=True, null=True)),
                ('ch_cuatrimestral', models.IntegerField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('ch_presencial', models.IntegerField(blank=True, null=True)),
                ('ch_distancia', models.IntegerField(blank=True, null=True)),
                ('ch_total', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('correlativas', models.ManyToManyField(blank=True, related_name='requerida_por', to='plan_de_estudio.materia')),
                ('plan_de_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='plan_de_estudio.plandeestudio')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['codigo'],
            },
        ),
    ]
