# Generated by Django 5.1.5 on 2025-01-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['materia_estudiante', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='MateriaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('final_obligatorio', models.BooleanField(default=True)),
                ('catedra', models.CharField(blank=True, max_length=200, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('comentarios_docente', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cursando', 'Cursando'), ('aprobada', 'Aprobada'), ('desaprobada', 'Desaprobada'), ('promocionada', 'Promocionada')], default='pendiente', max_length=50)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('metodo_aprobacion', models.CharField(blank=True, choices=[('final', 'Examen Final'), ('promocion', 'Promoción Directa'), ('equivalencia', 'Equivalencia')], max_length=50, null=True)),
                ('creditos_asignados', models.IntegerField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('dificultad', models.PositiveIntegerField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Materia Estudiante',
                'verbose_name_plural': 'Materias Estudiantes',
                'ordering': ['materia__anio', 'materia__codigo'],
            },
        ),
        migrations.CreateModel(
            name='MetaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('año_creacion', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
                'ordering': ['año_creacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_defecto', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso por defecto asignado a este tipo de evaluación', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('ciclo', models.CharField(blank=True, max_length=50, null=True)),
                ('cuatrimestre', models.IntegerField(blank=True, null=True)),
                ('condicion', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=1000)),
                ('formato_didactico', models.CharField(blank=True, max_length=50, null=True)),
                ('ch_semanal', models.IntegerField(blank=True, null=True)),
                ('ch_cuatrimestral', models.IntegerField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('ch_presencial', models.IntegerField(blank=True, null=True)),
                ('ch_distancia', models.IntegerField(blank=True, null=True)),
                ('ch_total', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('correlativas', models.ManyToManyField(blank=True, related_name='requerida_por', to='plan_de_estudio.materia')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['codigo'],
            },
        ),
    ]
