# Generated by Django 5.1.5 on 2025-02-04 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evento_academico', '0003_initial'),
        ('plan_de_estudio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materiaestudiante',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='plan_de_estudio.materia'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='materia_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='plan_de_estudio.materiaestudiante'),
        ),
        migrations.AddField(
            model_name='metamateria',
            name='materia_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.materiaestudiante'),
        ),
        migrations.AddField(
            model_name='metamateria',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento_academico.metaacademica'),
        ),
        migrations.AddField(
            model_name='materia',
            name='plan_de_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='plan_de_estudio.plandeestudio'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='plan_de_estudio.tipoevaluacion'),
        ),
        migrations.AlterUniqueTogether(
            name='materiaestudiante',
            unique_together={('estudiante', 'materia')},
        ),
        migrations.AlterUniqueTogether(
            name='metamateria',
            unique_together={('materia_estudiante', 'meta')},
        ),
    ]
