# Generated by Django 5.1.4 on 2024-12-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_de_estudio', '0001_initial'),
        ('planificadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandeestudio',
            name='planificador',
            field=models.OneToOneField(blank=True, help_text='Planificador asociado al plan de estudio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_de_estudio', to='planificadores.planificador'),
        ),
        migrations.AddField(
            model_name='materia',
            name='plan_de_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='plan_de_estudio.plandeestudio'),
        ),
    ]
