# Generated by Django 5.1.4 on 2025-01-10 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso_defecto', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso por defecto asignado a este tipo de evaluación', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('final_obligatorio', models.BooleanField(default=True)),
                ('catedra', models.CharField(blank=True, max_length=200, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cursando', 'Cursando'), ('aprobada', 'Aprobada'), ('desaprobada', 'Desaprobada'), ('promocionada', 'Promocionada')], default='pendiente', max_length=50)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('metodo_aprobacion', models.CharField(blank=True, choices=[('final', 'Examen Final'), ('promocion', 'Promoción Directa'), ('equivalencia', 'Equivalencia')], max_length=50, null=True)),
                ('creditos_asignados', models.IntegerField(blank=True, null=True)),
                ('comentarios_docente', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='plan_de_estudio.materia')),
            ],
            options={
                'verbose_name': 'Materia Estudiante',
                'verbose_name_plural': 'Materias Estudiantes',
                'ordering': ['materia__anio', 'materia__codigo'],
                'unique_together': {('estudiante', 'materia')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('materia_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='plan_de_estudio.materiaestudiante')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='plan_de_estudio.tipoevaluacion')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['materia_estudiante', 'tipo'],
            },
        ),
    ]
