# Generated by Django 5.1.5 on 2025-01-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0002_tipoevaluacion_materiaestudiante_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaestudiante',
            name='dificultad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
