# Generated by Django 5.1.5 on 2025-01-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_de_estudio', '0003_materiaestudiante_dificultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaestudiante',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
