# Generated by Django 5.1.5 on 2025-01-27 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento_academico', '0001_initial'),
        ('plan_de_estudio', '0004_materiaestudiante_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=1.0)),
                ('materia_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan_de_estudio.materiaestudiante')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento_academico.metaacademica')),
            ],
            options={
                'unique_together': {('materia_estudiante', 'meta')},
            },
        ),
    ]
