# Generated by Django 5.1.4 on 2024-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la sesión (Estudio, Repaso, Descanso, etc.)', max_length=255)),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Duración de la sesión en minutos para ser completada')),
                ('es_obligatoria', models.BooleanField(default=True, help_text='Indica si esta sesión es obligatoria para completar la tarea')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TareaTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la tarea', max_length=255)),
                ('cantidad_para_completar', models.PositiveIntegerField(help_text='Número total de sesiones necesarias para completar la tarea')),
                ('cantidad_completadas', models.PositiveIntegerField(default=0, help_text='Número de sesiones completadas actualmente')),
                ('esta_realizada', models.BooleanField(default=False, help_text='Indica si la tarea está completada')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
