# Generated by Django 5.1.4 on 2025-01-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text='Color asociado al estado.', max_length=7),
        ),
    ]
